# Generated by Django 2.2.7 on 2019-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('fc', models.CharField(max_length=250)),
                ('smallImg', models.ImageField(upload_to='players_image')),
                ('fullimg', models.ImageField(upload_to='players_image')),
                ('age', models.IntegerField()),
                ('inform', models.TextField()),
                ('position', models.CharField(max_length=250)),
            ],
        ),
    ]
