# Generated by Django 2.2.7 on 2019-11-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0002_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
