# Generated by Django 2.2.6 on 2019-12-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191208_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
