# Generated by Django 3.0 on 2019-12-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('bus_manufacturer', models.CharField(max_length=100)),
                ('bus_service', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Restly', 'Restly')], default='Sedentary', max_length=100)),
                ('bus_amount_seats', models.IntegerField()),
                ('bus_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('identity_card_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DateGoingOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('date_going_out', models.DateTimeField()),
                ('date_arriving', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('status', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.DateGoingOut')),
            ],
        ),
    ]
